# Generated by Django 5.0.7 on 2024-07-26 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sName', models.CharField(default='Default Name', max_length=100)),
                ('sAge', models.IntegerField(default=0)),
                ('address', models.CharField(default='Default Address', max_length=200)),
                ('image', models.ImageField(default='profile_images/default.jpg', upload_to='profile_images/')),
                ('email', models.EmailField(default='default@example.com', max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
